Rewrite: modular approach
berserktech/telebot pull request #7
Opened 2019-03-04 03:45 UTC by ghostbar

2019-03-04 03:53 UTC, sadasant commented on gh/content.go
> +	case "labeled",
Awesome!

2019-03-04 03:55 UTC, sadasant requested changes

2019-03-04 03:55 UTC, sadasant commented on gh/comment.go
> +package gh
Can you make this more explicit? as in `github`? Same with `telegram`. Please 🙏❤️

2019-03-04 04:05 UTC, ghostbar commented on gh/comment.go
> +package gh
The github library already calls itself github. That would create some issues. Better avoid it and leave it as `gh` and `tg` :-)

2019-03-04 04:05 UTC, ghostbar commented on gh/content.go
> +	case "labeled",
:-D

2019-03-04 04:28 UTC, sadasant commented
This is the problem that CircleCI is having: https://github.com/golang/go/issues/27056
I'm also having this myself. On it...

2019-03-04 07:12 UTC, sadasant commented
IMPORTANT: This doesn't work on Zeith.co. They use an older version:
https://github.com/zeit/now-builders/blob/master/packages/now-go/go-helpers.js#L93
and they disable GO111MODULE by default due to having `GO111MODULE=auto`.

I can manually set `GO111MODULE` to `on`, but 1.11 doesn't know how to mix go.mod with dependencies in GOPATH, see: https://golang.org/doc/go1.12#modules

> ... the go command now supports module-aware operations outside of a module directory, provided that those operations do not need to resolve import paths relative to the current directory or explicitly edit the go.mod file. ...

I did the silliest of pull requests to [zeit/now-builders](https://github.com/zeit/now-builders) just to bring awareness to the issue: https://github.com/zeit/now-builders/pull/247

2019-03-04 15:19 UTC, ghostbar commented
Going back to single-module repo for Zeit :-)

2019-03-05 04:44 UTC, sadasant approved these changes
🎉

2019-03-05 13:02 UTC, betacar approved these changes
💯

2019-03-05 13:24 UTC, merged